### ISSUE TITLE
Create an index per field

### ISSUE THREAD

**Issue by rstuart85** [Kapiche/caterpillar#18]
Right now we create a combined index across all text fields. In the case of metadata, we create an index of an index. We need to store an index per field for better search resolution.

**Comment by krisrogers** [comment]
This means breaking the index data structures (frequency, associations, etc) apart by field. Subsequently, methods like get_frequency() have to be updated to take a field parameter. [Refer to Lucene API]

**Comment by krisrogers** [comment]
When creating IndexWriter, search for indexed text fields and then create storage containers as per:
   ` text-field-name_associations`

For fold_terms & merge, run for individually every indexed text field

**Comment by krisrogers** [comment]
This is getting very messy...

The index stores temporary buffers:
`self.__new_frames, self.__new_documents`

Frames are only created via indexed text fields, which have separate storage structures. Hence, this buffer structure should be partitioned by text field. e.g. `self.__new_frames["text1"]`

However, documents can be added without text, so the document buffer cannot be partitioned by text field.

When calling the `delete_document` method, this poses a problem for the line:
`self.__rm_frames |= set(doc['_frames'])`
which needs to become:
`self.__rm_frames[text_field] |= set(doc['_frames'])`
but we can't get access to the `text_field` as documents aren't always text.

**Comment by krisrogers** [comment]
@rstuart85 Could you please comment on my above remarks?

**Comment by rstuart85** [comment]
> Frames are only created via indexed text fields, which have separate storage structures. Hence, this buffer structure should be partitioned by text field. e.g. self.__new_frames["text1"]

I don't follow this premise. Why do frames need to have separate storage structures? Frames are no different to documents. They should be stored in a central frame store. It's the indexes that are separate, not the storage containers.

Does this provide some clarity?

**Comment by krisrogers** [comment]
@rstuart85

Ok, now I'm confused, we already talked about prefixing the storage containers, for example `text1_associations`, but now you are saying it is the indexes that should be separate?

**Comment by rstuart85** [comment]
Each frame has a `_field` property. Is that what you are looking for?

Also, frames exist regardless if there is a indexed text field or not. In that case, `_field` is set to `None`. See [here](https://github.com/Kapiche/caterpillar/blob/master/caterpillar/processing/index.py#L665)

**Comment by krisrogers** [comment]
I was just confused by the terminology in your comment, but it doesn't matter.

If frames are not partitioned by text field then, `index.get_frame_count()`, which is implemented by `return self.__storage.get_container_len(IndexWriter.FRAMES_CONTAINER)`, seems to have no efficient way to constrain by text field..?

**Comment by rstuart85** [comment]
That's right. But, as part of this change (and in contrast to what I said before), we should have a separate frame store for each field. That will also mean having an "empty" frame store as well. But this is only an issue because we can't search by document. If we could search by document, we wouldn't need to have an "empty" frame store. So, just mark that piece of code to be fixed by #56.

**Comment by krisrogers** [comment]
Ok, but my original issue still stands, if frames are stored based on field, then the call to `delete_document` is problematic as we don't know which frame store to delete the frames from...

**Comment by rstuart85** [comment]
The frames for a document are listed on the document. The field that the frame is for is listed on the frame. All of this is available in `delete_document`. What am I missing? 

In the method that actually does the deleting, it already [fetches all frames](itinerary). All you need to do is adjust this to be done for each frame container. You can pass the full set of frame IDs to `get_container_items`. Those that don't exist will be returned as `None`.

**Comment by krisrogers** [comment]
Are you saying that on each call to `delete_document`, we query each separate frame store for the frame IDs? So we would need to keep a list of text fields somewhere in order to be able to query the field-based frame stores?

**Comment by rstuart85** [comment]
No, we don't need to keep a list somewhere. See [here](https://github.com/Kapiche/caterpillar/blob/master/caterpillar/processing/index.py#L122). And yes, that would appear to be the easiest solution right now.

**Comment by rstuart85** [comment]
Almost everything done from [here](https://github.com/Kapiche/caterpillar/blob/master/caterpillar/processing/index.py#L392) onwards in the delete method will need to be done per field on a document. You are going to have to iterate through the fields regardless to adjust the indexes (frequencies, associations, positions) for each field right? So doesn't doing the same for the frames container just naturally follow?

The pseudo code seems to be:

```
Add frame ids to be deleted to a set (like we are already doing)
When flush is called:
  for field self._schema.fields:
    fetch frames to be deleted (using self.__rm_frames as the keys argument)
    if field is indexed:
      adjust indexes for terms in the frame
    delete frames
```

There is a bit more complexity than that but you get the idea. Is there some other complication I am missing? The only complication that I can see is that we create frames even when there is no indexed field on a document added to the index, but we on;y do that because we haven't implemented document search yet. To implement document search, we need to do away with the `META_DATA` container idea and truly have an index per field (regardless if they are text or not).

**Comment by krisrogers** [comment]
[This](https://github.com/Kapiche/caterpillar/blob/master/caterpillar/storage/sqlite.py#L159) makes the above approach a bit clunky to implement not to mention inefficient for all the extra None checks...thoughts?

**Comment by rstuart85** [comment]
This code is already living past its expiry date. Shortly, I think it will be removed all together. So, for now, I'd just go with that approach so we can keep moving forward. #17 will remove this code.

**Comment by rstuart85** [comment]
We need document level and frame level frequencies for metadata fields.
