### ISSUE TITLE
Querystring wildcard matching should use fnmatch.filter

### ISSUE THREAD

**Issue by krisrogers** [Kapiche/caterpillar#22]

**Comment by rstuart85** [comment]
@krisrogers can you add a bit more context here? I don't really follow.

**Comment by krisrogers** [comment]
@rstuart85 I believe this was performance related, but not certain

**Comment by rstuart85** [comment]
@krisrogers more referring to the actual change itself. Using fnmatch (something targeted at Unix filesystems) for querying seems weird. Where did you intend on using it?

**Comment by krisrogers** [comment]
It supports glob style syntax for fast matching of wildcard expression
against a list of names (terms).
