### ISSUE TITLE
Don't split on punctuation by default

### ISSUE THREAD

**Issue by krisrogers** [Kapiche/caterpillar#36]
Current regexes for tokenisation are becoming unwieldy - we should move to retaining all punctuation by default, except cases explicitly specified:
- strip leading and trailing punctuation
- strip possessive suffix

Also, should fix https://github.com/Kapiche/research-portal/issues/49

**Comment by rstuart85** [comment]
The idea here will be to introduce a new default regex and leave the current one.

**Comment by rstuart85** [comment]
Fixed by #39
