### ISSUE TITLE
Paragraph tokenisation not working properly

### ISSUE THREAD

**Issue by rstuart85** [Kapiche/caterpillar#42]
Given this text:

```
7. Matt O’Sullivan, Qantas, “Frequent Flyers Program Changes Put
Loyalty at Risk,” Sydney Morning Herald, March 28, 2014, http:// www.smh.com.au/business/aviation/qantas-frequent-flyers-pro- 
gram-changes-put-loyalty-at-risk-20140328-35n22.html; Justin
Bachman, “Value of Frequent-Flyer Miles Will Soon Drop for
Delta and United Travelers,” Bloomberg Businessweek, December
19, 2013, http://www.businessweek.com/articles/2013-12-19/ value-of-frequent-flier-miles-will-soon-drop-for-delta-and-united-travelers.
```

There should only be one paragraph. Right now there are several. The issue appears to be the [\S]* part of the regex. I think this was born out of the weird line endings in Alice but it needs to be re-addressed.

**Comment by rstuart85** [comment]
Possibly [^\w\s] would work better. That is anything that isn't space or word like.

**Comment by rstuart85** [comment]
Changing it to that would break a paragraph ending like "economics.[11]" which is part of our test case. Thoughts @krisrogers ?

**Comment by krisrogers** [comment]
Well the case that causes the problem looks malformed to me, whilst the case the solution would break seems well-formed. That seems like an odd outcome....

**Comment by rstuart85** [comment]
Yea okay, point taken.
