### ISSUE TITLE
Need to deal with non-text fields in bi-gram discovery

### ISSUE THREAD

**Issue by krisrogers** [Kapiche/caterpillar#69]
Commit https://github.com/Kapiche/caterpillar/commit/3f9e980014face25c5769fd4a2c17c534ce23f0a updates `find_bi_gram_words` to not break if non-text frames are passed in.

It would be easy to apply this as a patch to master, or we could just require that only text frames are sent to `find_bi_gram_words`.

I can't do the latter in the chrysalis branch of caterpillar because `get_frames` doesn't support field parameterisation in that version, so revealed/chrysalis has no efficient way of selecting just the text frames to send to `find_bi_gram_words`.

**Comment by SamHames** [comment]
Superseded by the new find_bigrams function in the reader, so no longer necessary.
